# Generated by Django 4.2.23 on 2025-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('telegram', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
