# Generated by Django 4.2.23 on 2025-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telegram'),
        ),
    ]
